# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "hudi-ballista"
version = "54.0.0"
edition = "2024"
rust-version = "1.94.0"
license = "Apache-2.0"
description = "Apache Hudi read integration for Ballista"
repository = "https://github.com/apache/datafusion-ballista"
publish = false

[dependencies]
ballista-core = { path = "../../ballista/core", version = "54.0.0" }
datafusion = "55"
hudi-datafusion = { git = "https://github.com/wirybeaver/hudi-rs.git", rev = "c3e40091", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
ballista = { path = "../../ballista/client", version = "54.0.0", features = ["standalone"] }
hudi-test = { git = "https://github.com/wirybeaver/hudi-rs.git", rev = "c3e40091" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[workspace]
