store_type = "MEMORY_LOCALFILE"
grpc_port = 21100
http_port = 19998
coordinator_quorum = ["COORDINATOR_HOST:21000"]
tags = ["riffle", "datanode", "GRPC", "ss_v5"]

[memory_store]
capacity = "512M"

[localfile_store]
data_paths = ["/tmp/riffle-data"]
healthy_check_min_disks = 0
disk_max_concurrency = 2000
disk_high_watermark = 1.0

[hybrid_store]
memory_spill_high_watermark = 0.8
memory_spill_low_watermark = 0.2
memory_spill_max_concurrency = 500

[runtime_config]
read_thread_num = 5
write_thread_num = 10
grpc_thread_num = 5
http_thread_num = 2
default_thread_num = 2
dispatch_thread_num = 2

[log]
path = "/tmp/riffle-logs"
rotation = "Never"
