# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Ballista Web TUI

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
    paths:
      - "ballista/**"
      - "ballista-cli/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/web-tui.yml"
      - ".github/actions/setup-builder/**"
  pull_request:
    paths:
      - "ballista/**"
      - "ballista-cli/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/web-tui.yml"
      - ".github/actions/setup-builder/**"
  workflow_dispatch:

jobs:
  web-tui:
    name: Build Web TUI WASM32 application
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 1

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "stable"
          targets: "wasm32-unknown-unknown"

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 #2.9.1

      - name: Install Trunk
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: trunk@0.21.14

      - name: Install cargo-get
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-get@1.4.0

      - name: Get package.version
        id: cargo_metadata
        run: |
          set -x
          rsync --version
          BALLISTA_VERSION=$(cargo get --entry ballista/core/ package.version)
          echo "ballista_version=${BALLISTA_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build
        working-directory: ballista-cli
        run: |
          trunk build --cargo-profile release-nonlto --minify --locked \
            --no-default-features --features web

      - name: Deploy to Nightlies
        #if: ${{ github.ref == 'refs/heads/main' }}
        uses: burnett01/rsync-deployments@66257cad6bfeb2171d3b6bfa6c9a22279dd9c3a1 # v8.0.5
        with:
          switches: -rlptDvz
          path: target/web-tui/*
          remote_path: datafusion/ballista/tui/${{ steps.cargo_metadata.outputs.ballista_version }}/
          remote_host: https://nightlies.apache.org
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}


      - name: Upload WASM32 application
        uses: actions/upload-artifact@v7
        with:
          name: ballista-web-tui
          retention-days: 7
          path: target/web-tui/
